### ISSUE TITLE
SemiBold NAME table

### ISSUE THREAD

**Issue by davelab6** [itfoundry/hind-kochi#1]
HindKochi-SemiBold.otf has

```
<namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
  Hind Kochi
</namerecord>
<namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
  Bold
</namerecord>
```

I think this should be 

```
<namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
  Hind Kochi SemiBold
</namerecord>
<namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
  Regular
</namerecord>
```

**Comment by lianghai** [comment]
Yes, there was a bug in HindKit, related to style-linking. The bug has been fixed, and these OTFs will be updated when I push another round of builds.
However I actually plan to disable style-linking for all Hind families. Because with only the Bold weight linked to the Regular weight, the family (the Bold weight gets hidden in the font menu while the other 4 weights show) is actually pretty awkward to use in style-linking-relying environment (say, Microsoft Office), and Google Fonts targets more on web where style-linking is not used at all.

**Comment by davelab6** [comment]
Google docs is a main target and so I need  style linking of bold and
regular for users who download the fonts and use them in a mixed desktop
office work flow :)

**Comment by lianghai** [comment]
Ah, okay, so I'll keep style-linking on.
