### ISSUE TITLE
Wrong ligature rule for ന്റ

### ISSUE THREAD

**Issue by santhoshtr** [itfoundry/hind-kochi#4]
ന്റ(nta)  = ന + ് + റ. 

Currently it uses chillu n +ra  which is the sequence for ന്‍റ - pronounced as in Henry.

**Comment by lianghai** [comment]
I get what you mean here. But, just in case in the future: given the messy situation of fonts for Malayalam (all these fonts have different behaviors), please use images when you need to clearly explain a structure, or, as I personally perfer, explain a strucure with unambiguous description of glyphs (eg, glyph sequence `<Chillu N, below-base mark RRA>`).

So, about this `<chillu N, below-base mark RRA>` problem:

Currently in Hind Kochi, two character sequences are supported:
1. `<Chillu N, Virama, RRA>` — this is specified by the Unicode Standard, as you might know. But this sequence is not supported by either Windows or OS X's text engine yet.
2. `<NA, Virama, ZWJ, RRA>` — this is an alternative sequence that is compatible with Nirmala UI, which ensures Windows users can see glyph sequence `<chillu N, below-base mark RRA>` in text they input with Nirmala UI. I know this character sequence doesn't make sense, but it's provided to ensure compatibility. — However, because character sequence `<NA, Virama, ZWJ>` is also the legacy way of encoding Chillu N, to people who use the legacy Chillu sequences the font produces wrong structure for a character sequence (`<NA, Virama, ZWJ, RRA>`) that is meant to show glyph sequence `<Chillu N, RRA>` (side-by-side).

As for the character sequence `<NA, Virama, RRA>` you requested, yes, I did considered it. I shall add it to the font's OTL rules so the font provides another (and reasonable) fallback support that is common in the open source community.

**Comment by lianghai** [comment]
Hi @santhoshtr, in the latest build I have disabled the Nirmala-compatible rule (maybe only temporarily) and enabled the rule you requested.
